const nodemailer = require("nodemailer");
const pug = require("pug");
const htmltotext = require("html-to-text");
const promisify = require("es6-promisify")

var transport = nodemailer.createTransport({
 host: "smtp.mailtrap.io",
 port: 2525,
 auth: {
   user: "c16f248403ff81", //generated by Mailtrap
   pass: "6f70203545eb76" //generated by Mailtrap
 }
});

mailOptions ={
 from : 'kirandeepstar123@gmail.com',
 to: 'kiran111candy@gmail.com',
 subject : 'Just trying things out',
 html : ' Hey I love YOU ---',
 text : "Hey i love  you ..."
}


// transport.sendMail(mailOptions, function(error, info){
//  if (error) {
//    console.log(error);
//  } else {
//    console.log('Email sent: ' + info.response);
//  }
// });


exports.send = async (options) => {
 const mailOptions = {
  from : "kirandeepstar123@gmail.com",
  to : options.user.email,
  subject : options.subject,
  html : 'This will be filled later',
  text : " This will be filled later"
 }
 const sendMail = promisify(transport.sendMail,transport)
 return sendMail(mailOptions)
}