[build]

  base = "/"

  publish = "/"

  command = "echo 'default context'"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[context.master]
  publish = "/"
  command = "npm run start"
  environment = { NODE_VERSION = "12.0.0" }
